### PR TITLE
WIP - summer cleaning

### PR DESCRIPTION
**Pull request by ear**
Work in progress.

I started with `Main.hs` and a 🍷—here's the results so far.

I think I caught a couple bugs and put in a couple of improvements.

### CODE REVIEW

**Comment by rexim** [comment]
@ear While you're still working on this PR, please keep in mind https://github.com/tsoding/HyperNerd/blob/master/CONTRIBUTING.md Thanks for donating your personal time to this project!

**Comment by ear** [comment]
@rexim ah good point.

I wanted to put the code on here to let you see what I had in mind, mostly. I am curious what you think.

Style:

- I tried to keep it readable but without 18 letter names everywhere.
- `runIO` in the "more natural" style of `runState` (parameter position)
- Could understand the Free Monad constructors' behaviors except timeout: more readable names to help
- `RecordWildCards` is the greatest invention ever

Behavior:

- Made `ErrorEff` print on stderr
- Moved from stitching together stuff with `String` to using `Data.Text.{IO,Encoding}` (since it natively supports `Text` where you seemed to need it …and learned about it in the meanwhile!)

"Bugs":

- `advanceTimeouts` was using `(<0)` which would miss timeouts elapsing exactly at that time: `(<=0)`
- `clientID <- return $ T.encodeUtf8 $ configClientId bsConfig` does not fail when there isn't one but that might be intended behavior (I am not sure what the best experience is)

Ideas:

- `advanceTimeouts` was `foldl (… >>= …)` which is `foldM` do you like it? I am also a fan of `ViewPatterns` which lets us `map snd -> ripe` and shove it in a corner so that it doesn't look as garish. Compare:

```hs
    (map snd -> ripe, unripe) = partition ((<=0) . fst) $ first (subtract dt) <$> bsTimeouts

    (ripe, unripe) = first (map snd) <$> partition ((<=0) . fst) $ first (subtract dt) <$> bsTimeouts
```

I'd like to know what you think about things like this, I am doing what I would do to my own code, I think I'm going to run this bot going forward so I am taking an interest!

**Comment by rexim** [comment]
@ear 

> I am curious what you think.

All of these sound like good candidates for different issues where they can be discussed separately in a more disciplined and organized manner and later fixed in parallel by several people.

**P.S.** I'm really sorry for enforcing discipline here. Unlike https://github.com/tsoding/ray-tracer HyperNerd is a very crucial part of Tsoding project infrastructure. And I need to make sure that the bot works according to the "business needs" (I hate these words, but can't find better ones). Don't get me wrong. I'm very open to suggestions, pull requests, issues, etc and I want the bot to be reusable for as many people as possible. But let's just do that in a more organized way.

**P.P.S** If you plan to use this bot for yourself, but your "business needs" conflict with mine, feel free to fork it according to MIT license. I would even encourage you to do that in case of conflict of interest. Again, sorry for bringing this all up. I've been in all of these situations so many times and I just want us to be on the same page upfront. Thank you again for donating your personal time to this project. :)

**Comment by rexim** [comment]
@ear also, here is the trick on how to bypass PR size limitation. You may find it useful. https://github.com/tsoding/HyperNerd/commit/9021c990bfe1473d0e5b068c94fbe64fc00d24f5

**Comment by rexim** [comment]
@ear do you plan to finish this PR? It doesn't violate any [Contribution Rules][rules] so far. The problems I see

- Marked as WIP, so I assume it's not finished
- CI is not passing
- Changes have conflicts with the current master

If you fix the above problems I review it. If you created this PR to suggest ideas then for that we have issues. I believe PRs are for code that is intended to be merge into master.

[rules]: https://github.com/tsoding/HyperNerd/blob/34cdb12c2e43bab7def689287dc3ef196b929fd1/CONTRIBUTING.md

**Pull request closed without merging**
